### ISSUE TITLE
use bonding_account instead of shard naming for onchain balances

### ISSUE THREAD

**Issue by brenzi** [scs/pallet-substratee-registry#6]
Your parameter naming `shard` is misleading bacause there are no shards on-chain. For better readability, please use `bonding_account` which happens to by bit-equivalent with the `ShardIdentifier` the enclaves operate on. Please also indicate in function docs that there is no private key to that account - instead it is in debitable by members of the enclave registry for that shard.

Also, `incognito_account` should be `incognito_account_encrypted` to indicate that it is opaque to the runtime.

Do you use `T::Currency` to be generic? that's fine, but in our case it will be pallet_balances

https://github.com/scs/pallet-substratee-registry/blob/cf614c4b2caba2f5451b8ee614bf69c5bd21f016/src/lib.rs#L163-L179

**Comment by clangenb** [comment]
I agree, that this implicit information needs to be closely documented in the function call.

I was unsure whether the argument should be named shard or enclave account. :)

Regarding the `T::Currency` usage. I simply did not know how to do better, the only examples i found used the `Currency` module
